<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>vatsys.RadarRefreshPlugin</AssemblyName>
    <RootNamespace>vatsys.RadarRefreshPlugin</RootNamespace>
    <PlatformTarget>x86</PlatformTarget>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>

    <Reference Include="vatsys">
      <HintPath>C:\Program Files (x86)\vatSys\bin\vatSys.exe</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="System.ComponentModel.Composition" />

  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>